### PR TITLE
#6 Added favicon.png to index.html page

### PR DESCRIPTION
**Pull request by ccrowley96**

### CODE REVIEW

**Comment by ccrowley96** [comment]
@RobertWSaunders I added the favicon-webpack-plugin!  I also added the dependency 'cross-env' for running the build and run scripts from windows.  This allows us to use: 'npm run build/start/dev' on windows without changing the script syntax for NODE_ENV.  

Let me know what you think about the favicon.  I noticed that for the generator, you need to input a relatively large resolution file, because favicons up to 1535x2008px are being generated.  I went with a 512x512px favicon as the input to the generator.    The 32x32px PNG from the previous commit on this PR looked slightly better in the chrome tabs, but that won't be compatible on other browsers / devices.

**Comment by zackharley** [comment]
@ccrowley96 Can you add a screenshot of the folder containing the outputted favicons?

**Comment by ccrowley96** [comment]
@zackharley 
screen shot 2017-11-01 at 8 35 23 pm

**Comment by ccrowley96** [comment]
@zackharley, should be good to go!  Also, my google email is ccrowley96@gmail.com for the test site 👍

**Comment by zackharley** [comment]
@ccrowley96  Added you. Let me know if you can access test.qhacks.io

**Pull request merged**
