### PR TITLE
Application successful reminder email

### PR DESCRIPTION
**Pull request by zackharley**

### CODE REVIEW

**Comment by zackharley** [comment]
NPM issues have been the problem here. I couldn’t install any dependencies due to node_modules and package-lock.json

**Comment by RobertWSaunders** [comment]
I'm looking into ways we can improve this, this will just keep happening. I don't know the proper way to handle this.

**Comment by zackharley** [comment]
ignore package locks?

**Comment by RobertWSaunders** [comment]
Yeah lets do that

**Pull request merged**
